target("hello")
    set_languages("c++23")
    set_kind("binary")
    set_toolchains("clang")
    add_files("src/main.cc")
    add_cxxflags("-stdlib=libc++")
    add_ldflags("-stdlib=libc++")
    add_cxxflags("-fprebuilt-module-path=/usr/share/libc++/v1")
